---
title: "Descriptive Statistics"
output: html_document
---

DESCRIPTIVE STATISTICS 
Table 1
More boxplots
etc.
Box Cox
2 people:Stella, Vasili


```{r message=FALSE, warning=FALSE}
library(tidyverse)
library(arsenal)
library(MASS)
library(patchwork)
```

Read in hate crime data.

```{r message=FALSE, warning=FALSE}
hate_crimes_df = read.csv("./data/HateCrimes.csv") %>%
  janitor::clean_names() %>%
  rename(perc_pop_hs = perc_population_with_high_school_degree) %>% 
  mutate(hate_crimes_per_100k_splc = as.numeric(hate_crimes_per_100k_splc)) %>%
  drop_na(hate_crimes_per_100k_splc) %>%
  mutate(unemployment = as_factor(unemployment),
         urbanization = as_factor(urbanization))
```

Descriptive Statistics:

```{r}
h_c_df =
  hate_crimes_df %>%
  rename(
    Unemployment = "unemployment",
    Urbanization = "urbanization",
    "Median Household Income" = "median_household_income",
    "% Adults >25yrs With HS Degree" = "perc_pop_hs",
    "% of Population Not U.S. Citizens" = "perc_non_citizen",
    "% of Population Not White" = "perc_non_white",
    "Gini Index" = "gini_index",
    "Hate Crime Rate Per 100k" = "hate_crimes_per_100k_splc"
  ) %>%
  dplyr::select(-state)

my_controls = tableby.control(
               total = T,
               test=F,  
               numeric.stats = c("meansd", "medianq1q3", "range", "Nmiss2"),
               cat.stats = c("countpct", "Nmiss2"),
               stats.labels = list(
               meansd = "Mean (SD)",
               medianq1q3 = "Median (Q1, Q3)",
               range = "Min - Max",
               Nmiss2 = "Missing",
               countpct = "N (%)"))

tab1 = tableby( ~ ., data = h_c_df, control = my_controls)

summary(tab1) %>% 
  knitr::kable()

xtabs(~ Unemployment + Urbanization, data = h_c_df)
```

Box-Cox Transformation

```{r}
# log transformation
hate_crimes_df <- hate_crimes_df %>%
  mutate(hate_crimes_log = log(hate_crimes_per_100k_splc))

# Box Cox for multiple regression
mult_fit_1 = lm(hate_crimes_per_100k_splc ~ unemployment + urbanization + median_household_income + perc_pop_hs + perc_non_citizen + gini_index + perc_non_white, data = hate_crimes_df)
summary(mult_fit_1)

boxcox(mult_fit_1)
plot(mult_fit_1)
```

Residuals Boxplot

```{r message=FALSE, warning=FALSE}
resid_1 = residuals(mult_fit_1)
resid_1_df <- data.frame(resid_1 = resid_1)
ggplot(resid_1_df, aes(x = factor(0), y = resid_1)) +
geom_boxplot() + xlab(" ") + ylab("Residuals") + ggtitle("Residual Box Plot") +
theme(axis.text.x = element_blank())
```

Distribution of gini_index and median_household_income

```{r}
gini_dist =
  hate_crimes_df %>%
    ggplot(aes(x = gini_index)) +
    geom_density()

median_dist =
  hate_crimes_df %>%
  ggplot(aes(x = median_household_income)) +
  geom_density()

gini_dist + median_dist
```

Stratify based on unemployment, and urbanization just to see...

```{r}
unemploy_high =
  hate_crimes_df %>%
    filter(unemployment == "high")

unemploy_low =
  hate_crimes_df %>%
    filter(unemployment == "low")

mod_unemply_high = lm(hate_crimes_log ~ gini_index, data = unemploy_high)
summary(mod_unemply_high)

mod_unemply_low = lm(hate_crimes_log ~ gini_index, data = unemploy_low)
summary(mod_unemply_low)

urban_high =
  hate_crimes_df %>%
    filter(urbanization == "high")

urban_low =
  hate_crimes_df %>%
    filter(urbanization == "low")

mod_urban_high = lm(hate_crimes_log ~ gini_index, data = urban_high)
summary(mod_urban_high)

mod_urban_low = lm(hate_crimes_log ~ gini_index, data = urban_low)
summary(mod_urban_low)

```

NOTHING...
